#!/bin/bash

DOCKER_BIP=$(curl http://metadata/computeMetadata/v1/instance/attributes/bip -H "Metadata-Flavor: Google")
API_SERVER=$(curl http://metadata/computeMetadata/v1/instance/attributes/apiserver -H "Metadata-Flavor: Google")

## Download binaries.
mkdir -p /opt/bin
curl https://kuar.io/docker -o /opt/bin/docker
curl https://kuar.io/kubelet -o /opt/bin/kubelet
curl https://kuar.io/kube-proxy -o /opt/bin/kube-proxy
chmod +x /opt/bin/docker /opt/bin/kubelet /opt/bin/kube-proxy

## docker
cat <<EOF > /etc/systemd/system/docker.service
[Unit]
Description=Docker Application Container Engine
Documentation=http://docs.docker.io

[Service]
ExecStart=/opt/bin/docker --daemon \
  --bip=${DOCKER_BIP} \
  --iptables=false \
  --ip-masq=false \
  --host=unix:///var/run/docker.sock \
  --storage-driver=overlay
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

## kubelet
cat <<EOF > /etc/systemd/system/kubelet.service
[Unit]
Description=Kubernetes Kubelet
Documentation=https://github.com/GoogleCloudPlatform/kubernetes

[Service]
ExecStart=/opt/bin/kubelet \
 --api-servers=${API_SERVERS} \
 --cluster-dns=10.200.20.10 \ 
 --cluster-domain=cluster.local \
 --v=2
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

## kube-proxy

cat <<EOF > /etc/systemd/system/kube-proxy.service
[Unit]
Description=Kubernetes Proxy
Documentation=https://github.com/GoogleCloudPlatform/kubernetes

[Service]
ExecStart=/opt/bin/kube-proxy --master=${API_SERVERS} --v=2
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

## Start systemd units.
systemctl daemon-reload
systemctl enable docker
systemctl enable kubelet
systemctl enable kube-proxy
systemctl start docker
systemctl start kubelet
systemctl start kube-proxy
